#ifndef MATERIAL_COLOR_H
#define MATERIAL_COLOR_H

#include "utils/string.h"
#include "utils/types.h"
#include "material/const.h"

#define COLOR_SEM_LISTS \
    _DISPATCHER(COLOR_SEM_OUTLINE, COLOR_SEMSTR_OUTLINE, sizeof(COLOR_SEMSTR_OUTLINE), COLOR_SEMT_NONE, COLOR_SEMP_NONE, FALSE, TRUE) \
    _DISPATCHER(COLOR_SEM_WHITE, COLOR_SEMSTR_WHITE, sizeof(COLOR_SEMSTR_WHITE), COLOR_SEMT_NONE, COLOR_SEMP_NONE, FALSE, TRUE) \
    _DISPATCHER(COLOR_SEM_MOUTH, COLOR_SEMSTR_MOUTH, sizeof(COLOR_SEMSTR_MOUTH), COLOR_SEMT_NONE, COLOR_SEMP_NONE, FALSE, TRUE) \
    _DISPATCHER(COLOR_SEM_LIGHT_SKIN, COLOR_SEMSTR_LIGHT_SKIN, sizeof(COLOR_SEMSTR_LIGHT_SKIN), COLOR_SEMT_SKIN, COLOR_SEMP_CREAM, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_NORMAL_SKIN, COLOR_SEMSTR_NORMAL_SKIN, sizeof(COLOR_SEMSTR_NORMAL_SKIN), COLOR_SEMT_SKIN, COLOR_SEMP_CREAM, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_DARK_SKIN, COLOR_SEMSTR_DARK_SKIN, sizeof(COLOR_SEMSTR_DARK_SKIN), COLOR_SEMT_SKIN, COLOR_SEMP_CREAM, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_IRON, COLOR_SEMSTR_NORMAL_IRON, sizeof(COLOR_SEMSTR_NORMAL_IRON), COLOR_SEMT_IRON, COLOR_SEMP_GRAY, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_DARK_IRON, COLOR_SEMSTR_DARK_IRON, sizeof(COLOR_SEMSTR_DARK_IRON), COLOR_SEMT_IRON, COLOR_SEMP_GRAY, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_BLACK_IRON, COLOR_SEMSTR_BLACK_IRON, sizeof(COLOR_SEMSTR_BLACK_IRON), COLOR_SEMT_IRON, COLOR_SEMP_GRAY, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_LIGHT_WOOD, COLOR_SEMSTR_LIGHT_WOOD, sizeof(COLOR_SEMSTR_LIGHT_WOOD), COLOR_SEMT_WOOD, COLOR_SEMP_BROWN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_WOOD, COLOR_SEMSTR_NORMAL_WOOD, sizeof(COLOR_SEMSTR_NORMAL_WOOD), COLOR_SEMT_WOOD, COLOR_SEMP_BROWN, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_DARK_WOOD, COLOR_SEMSTR_DARK_WOOD, sizeof(COLOR_SEMSTR_DARK_WOOD), COLOR_SEMT_WOOD, COLOR_SEMP_BROWN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_LIGHT_PALE_WOOD, COLOR_SEMSTR_LIGHT_PALE_WOOD, sizeof(COLOR_SEMSTR_LIGHT_PALE_WOOD), COLOR_SEMT_PALE_WOOD, COLOR_SEMP_BROWN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_PALE_WOOD, COLOR_SEMSTR_NORMAL_PALE_WOOD, sizeof(COLOR_SEMSTR_NORMAL_PALE_WOOD), COLOR_SEMT_PALE_WOOD, COLOR_SEMP_BROWN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_DARK_PALE_WOOD, COLOR_SEMSTR_DARK_PALE_WOOD, sizeof(COLOR_SEMSTR_DARK_PALE_WOOD), COLOR_SEMT_PALE_WOOD, COLOR_SEMP_BROWN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_STONE, COLOR_SEMSTR_NORMAL_STONE, sizeof(COLOR_SEMSTR_NORMAL_STONE), COLOR_SEMT_STONE, COLOR_SEMP_GRAY, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_DARK_STONE, COLOR_SEMSTR_DARK_STONE, sizeof(COLOR_SEMSTR_DARK_STONE), COLOR_SEMT_STONE, COLOR_SEMP_GRAY, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_LIGHT_LEAF, COLOR_SEMSTR_LIGHT_LEAF, sizeof(COLOR_SEMSTR_LIGHT_LEAF), COLOR_SEMT_LEAF, COLOR_SEMP_GREEN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_LEAF, COLOR_SEMSTR_NORMAL_LEAF, sizeof(COLOR_SEMSTR_NORMAL_LEAF), COLOR_SEMT_LEAF, COLOR_SEMP_GREEN, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_DARK_LEAF, COLOR_SEMSTR_DARK_LEAF, sizeof(COLOR_SEMSTR_DARK_LEAF), COLOR_SEMT_LEAF, COLOR_SEMP_GREEN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_LIGHT_PALE_LEAF, COLOR_SEMSTR_LIGHT_PALE_LEAF, sizeof(COLOR_SEMSTR_LIGHT_PALE_LEAF), COLOR_SEMT_PALE_LEAF, COLOR_SEMP_GREEN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_PALE_LEAF, COLOR_SEMSTR_NORMAL_PALE_LEAF, sizeof(COLOR_SEMSTR_NORMAL_PALE_LEAF), COLOR_SEMT_PALE_LEAF, COLOR_SEMP_GREEN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_DARK_PALE_LEAF, COLOR_SEMSTR_DARK_PALE_LEAF, sizeof(COLOR_SEMSTR_DARK_PALE_LEAF), COLOR_SEMT_PALE_LEAF, COLOR_SEMP_GREEN, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_EVIL_RED, COLOR_SEMSTR_EVIL_RED, sizeof(COLOR_SEMSTR_EVIL_RED), COLOR_SEMT_NONE, COLOR_SEMP_RED, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_BRICK_RED, COLOR_SEMSTR_BRICK_RED, sizeof(COLOR_SEMSTR_BRICK_RED), COLOR_SEMT_NONE, COLOR_SEMP_RED, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_NORMAL_GOLD, COLOR_SEMSTR_NORMAL_GOLD, sizeof(COLOR_SEMSTR_NORMAL_GOLD), COLOR_SEMT_GOLD, COLOR_SEMP_YELLOW, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_DARK_GOLD, COLOR_SEMSTR_DARK_GOLD, sizeof(COLOR_SEMSTR_DARK_GOLD), COLOR_SEMT_GOLD, COLOR_SEMP_YELLOW, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_DIAMOND, COLOR_SEMSTR_NORMAL_DIAMOND, sizeof(COLOR_SEMSTR_NORMAL_DIAMOND), COLOR_SEMT_DIAMOND, COLOR_SEMP_BLUE, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_DARK_DIAMOND, COLOR_SEMSTR_DARK_DIAMOND, sizeof(COLOR_SEMSTR_DARK_DIAMOND), COLOR_SEMT_DIAMOND, COLOR_SEMP_BLUE, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_NORMAL_WATER, COLOR_SEMSTR_NORMAL_WATER, sizeof(COLOR_SEMSTR_NORMAL_WATER), COLOR_SEMT_WATER, COLOR_SEMP_BLUE, TRUE, TRUE) \
    _DISPATCHER(COLOR_SEM_DARK_WATER, COLOR_SEMSTR_DARK_WATER, sizeof(COLOR_SEMSTR_DARK_WATER), COLOR_SEMT_WATER, COLOR_SEMP_BLUE, TRUE, FALSE) \
    _DISPATCHER(COLOR_SEM_CRACK, COLOR_SEMSTR_CRACK, sizeof(COLOR_SEMSTR_CRACK), COLOR_SEMT_CRACK, COLOR_SEMP_GRAY, TRUE, TRUE) \
\

#define COLOR_SEMT_LISTS \
    _DISPATCHER(COLOR_SEMT_SKIN, COLOR_SEMTSTR_SKIN, sizeof(COLOR_SEMTSTR_SKIN)) \
    _DISPATCHER(COLOR_SEMT_IRON, COLOR_SEMTSTR_IRON, sizeof(COLOR_SEMTSTR_IRON)) \
    _DISPATCHER(COLOR_SEMT_WOOD, COLOR_SEMTSTR_WOOD, sizeof(COLOR_SEMTSTR_WOOD)) \
    _DISPATCHER(COLOR_SEMT_PALE_WOOD, COLOR_SEMTSTR_PALE_WOOD, sizeof(COLOR_SEMTSTR_PALE_WOOD)) \
    _DISPATCHER(COLOR_SEMT_STONE, COLOR_SEMTSTR_STONE, sizeof(COLOR_SEMTSTR_STONE)) \
    _DISPATCHER(COLOR_SEMT_LEAF, COLOR_SEMTSTR_LEAF, sizeof(COLOR_SEMTSTR_LEAF)) \
    _DISPATCHER(COLOR_SEMT_PALE_LEAF, COLOR_SEMTSTR_PALE_LEAF, sizeof(COLOR_SEMTSTR_PALE_LEAF)) \
    _DISPATCHER(COLOR_SEMT_GOLD, COLOR_SEMTSTR_GOLD, sizeof(COLOR_SEMTSTR_GOLD)) \
    _DISPATCHER(COLOR_SEMT_DIAMOND, COLOR_SEMTSTR_DIAMOND, sizeof(COLOR_SEMTSTR_DIAMOND)) \
    _DISPATCHER(COLOR_SEMT_WATER, COLOR_SEMTSTR_WATER, sizeof(COLOR_SEMTSTR_WATER)) \
    _DISPATCHER(COLOR_SEMT_CRACK, COLOR_SEMTSTR_CRACK, sizeof(COLOR_SEMTSTR_CRACK)) \
\

#define COLOR_SEMP_LISTS \
    _DISPATCHER(COLOR_SEMP_CREAM, COLOR_SEMPSTR_CREAM, sizeof(COLOR_SEMPSTR_CREAM)) \
    _DISPATCHER(COLOR_SEMP_GRAY, COLOR_SEMPSTR_GRAY, sizeof(COLOR_SEMPSTR_GRAY)) \
    _DISPATCHER(COLOR_SEMP_BROWN, COLOR_SEMPSTR_BROWN, sizeof(COLOR_SEMPSTR_BROWN)) \
    _DISPATCHER(COLOR_SEMP_GREEN, COLOR_SEMPSTR_GREEN, sizeof(COLOR_SEMPSTR_GREEN)) \
    _DISPATCHER(COLOR_SEMP_RED, COLOR_SEMPSTR_RED, sizeof(COLOR_SEMPSTR_RED)) \
    _DISPATCHER(COLOR_SEMP_YELLOW, COLOR_SEMPSTR_YELLOW, sizeof(COLOR_SEMPSTR_YELLOW)) \
    _DISPATCHER(COLOR_SEMP_BLUE, COLOR_SEMPSTR_BLUE, sizeof(COLOR_SEMPSTR_BLUE)) \
\

#define _DISPATCHER(NAME, _STR, _STRLEN, _SEMT, _SEMP, _IFAM, _IREQ) NAME,
typedef enum color_sem {
    COLOR_SEM_LISTS
    COLOR_SEM_NONE
} color_sem_t;
#undef _DISPATCHER

#define _DISPATCHER(NAME, _STR, _STRLEN) NAME,
typedef enum color_semt {
    COLOR_SEMT_LISTS
    COLOR_SEMT_NONE
} color_semt_t;
#undef _DISPATCHER

#define _DISPATCHER(NAME, _STR, _STRLEN) NAME,
typedef enum color_semp {
    COLOR_SEMP_LISTS
    COLOR_SEMP_NONE
} color_semp_t;
#undef _DISPATCHER

#define COLOR_SEM_TOTAL         (COLOR_SEM_CRACK - COLOR_SEM_OUTLINE + 1)

typedef uint8_t color_id_t;
typedef uint8_t colorfam_id_t;

typedef struct color {
    union {
        uint8_t red;
        uint8_t r;
        uint8_t hue;
        uint8_t h;
    };
    union {
        uint8_t green;
        uint8_t g;
        uint8_t saturation;
        uint8_t s;
    };
    union {
        uint8_t blue;
        uint8_t b;
        uint8_t lightness;
        uint8_t l;
    };
} color_t;

typedef struct colorfam {
    color_id_t darken;
    color_id_t normal;
    color_id_t lighten;
    uint8_t flag;
} colorfam_t;

typedef struct colorchn_opt {
    string_view_t name;
    color_sem_t *entries;
    uint8_t length;
} colorchn_opt_t;

typedef struct colorchn {
    string_view_t name;
    struct {
        colorchn_opt_t *entries;
        uint8_t length;
    };
} colorchn_t;

void colorchn_opt_init(colorchn_opt_t *colorchn_opt, uint8_t total_colorfam);
void colorchn_opt_set_name(colorchn_opt_t *colorchn_opt, const string_view_t *name);
FORCE_INLINE void colorchn_opt_push_colorsem(colorchn_opt_t *colorchn_opt, color_sem_t colorsem);
FORCE_INLINE color_sem_t colorchn_opt_get_colorsem(colorchn_opt_t *colorchn_opt, uint8_t index);

void colorchn_init(colorchn_t *colorchn, uint8_t total_opts);
void colorchn_set_name(colorchn_t *colorchn, const string_view_t *name);
FORCE_INLINE colorchn_opt_t *colorchn_alloc_opt(colorchn_t *colorchn);
FORCE_INLINE color_sem_t colorchn_get_colorsem(colorchn_t *colorchn, uint8_t index, uint8_t colorpos);

FORCE_INLINE void colorchn_opt_push_colorsem(colorchn_opt_t *colorchn_opt, color_sem_t colorsem) {
    colorchn_opt->entries[colorchn_opt->length++] = colorsem;
}

FORCE_INLINE color_sem_t colorchn_opt_get_colorsem(colorchn_opt_t *colorchn_opt, uint8_t index) {
    return colorchn_opt->entries[index];
}

FORCE_INLINE colorchn_opt_t *colorchn_alloc_opt(colorchn_t *colorchn) {
    return colorchn->entries + colorchn->length++;
}

FORCE_INLINE color_sem_t colorchn_get_colorsem(colorchn_t *colorchn, uint8_t index, uint8_t colorpos) {
    return colorchn->entries[index].entries[colorpos];
}

#endif /* MATERIAL_COLOR_H */ 